//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventos.Info.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int EventoId { get; set; }
        public Nullable<int> OrganizadorId { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public string Nombre { get; set; }
        public string Fecha { get; set; }
        public string Lugar { get; set; }
        public string Hora { get; set; }
        public Nullable<int> Precio { get; set; }
        public string Descripcion { get; set; }
        public string PosterUrl { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Organizador Organizador { get; set; }
    }
}
