//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventos.Info.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizador
    {
        public Organizador()
        {
            this.Evento = new HashSet<Evento>();
        }
    
        public int OrganizadorId { get; set; }
        public string Nombre { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string Correo { get; set; }
    
        public virtual ICollection<Evento> Evento { get; set; }
    }
}
