//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventos.Info.UI.EventoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evento", Namespace="http://schemas.datacontract.org/2004/07/Eventos.Info.Negocio")]
    [System.SerializableAttribute()]
    public partial class Evento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CategoriaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrganizadorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosterUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoriaId {
            get {
                return this.CategoriaIdField;
            }
            set {
                if ((this.CategoriaIdField.Equals(value) != true)) {
                    this.CategoriaIdField = value;
                    this.RaisePropertyChanged("CategoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventoId {
            get {
                return this.EventoIdField;
            }
            set {
                if ((this.EventoIdField.Equals(value) != true)) {
                    this.EventoIdField = value;
                    this.RaisePropertyChanged("EventoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lugar {
            get {
                return this.LugarField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarField, value) != true)) {
                    this.LugarField = value;
                    this.RaisePropertyChanged("Lugar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrganizadorId {
            get {
                return this.OrganizadorIdField;
            }
            set {
                if ((this.OrganizadorIdField.Equals(value) != true)) {
                    this.OrganizadorIdField = value;
                    this.RaisePropertyChanged("OrganizadorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PosterUrl {
            get {
                return this.PosterUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PosterUrlField, value) != true)) {
                    this.PosterUrlField = value;
                    this.RaisePropertyChanged("PosterUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EventoServiceReference.IEventoService")]
    public interface IEventoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventoService/BuscarUltimosEventos", ReplyAction="http://tempuri.org/IEventoService/BuscarUltimosEventosResponse")]
        Eventos.Info.UI.EventoServiceReference.Evento[] BuscarUltimosEventos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventoService/BuscarUltimosEventos", ReplyAction="http://tempuri.org/IEventoService/BuscarUltimosEventosResponse")]
        System.Threading.Tasks.Task<Eventos.Info.UI.EventoServiceReference.Evento[]> BuscarUltimosEventosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventoServiceChannel : Eventos.Info.UI.EventoServiceReference.IEventoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventoServiceClient : System.ServiceModel.ClientBase<Eventos.Info.UI.EventoServiceReference.IEventoService>, Eventos.Info.UI.EventoServiceReference.IEventoService {
        
        public EventoServiceClient() {
        }
        
        public EventoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Eventos.Info.UI.EventoServiceReference.Evento[] BuscarUltimosEventos() {
            return base.Channel.BuscarUltimosEventos();
        }
        
        public System.Threading.Tasks.Task<Eventos.Info.UI.EventoServiceReference.Evento[]> BuscarUltimosEventosAsync() {
            return base.Channel.BuscarUltimosEventosAsync();
        }
    }
}
